### ISSUE TITLE
Add file autogen.sh or update build instructions to describe autotools

### ISSUE THREAD

**Issue by pietsch** [unpaper/unpaper#19]
Currently it is very hard to build unpaper unless you are fluent with the autotools that generate the configure script. The current documentation assumes that the source distribution contains such a file.

You probably have something like a autogen.sh script lying around. Here is what finally generated a configure script for me:

$ libtoolize --force
$ aclocal
$ automake --force-missing --add-missing
$ autoconf

**Comment by Dominique-M** [comment]
“And for everybody else autoreconf -fi will be enough anyway.”
This is not obvious for people who are not used to building from source. (Of course the instruction ./configure didn’t work. It took me ages to learn about autoconf; to find why it didn’‘t work either; to learn about autoreconf.) Not everybody reads this thread. I suggest to add autoreconf -fi before the line ./configure under Building instructions in README.md.
