### ISSUE TITLE
Using GPU on Mac

### ISSUE THREAD

**Issue by thawatchai** [unpaper/unpaper#222]
From Activity Monitor, I see that unpaper doesn't use GPU at all. I think it might speed up if unpaper can use GPU on Mac. Can unpaper use GPU? If it already has the ability, how can I configure it on a Mac? I've installed it using Homebrew.

**Comment by Flameeyes** [comment]
unpaper definitely doesn't use GPU, there's nothing in it that can possibly use GPU as it stand. I'm working on a new release that should come out some time this year that *might* be able to make better use of multi-core GPUs, but that's not going to be significantly faster, and in any case it won't have any GPU to use.
