### ISSUE TITLE
unpaper reports Warning: using insecure memory!

### ISSUE THREAD

**Issue by pheitman** [unpaper/unpaper#225]
I am using unpaper as part of the paperless-ngx docker image. When unpaper is run (e.g. unpaper --version) it always prints a warning before the version:

Warning: using insecure memory!
7.0.0

This is messing up paperless-ngx since the expected version is not the first thing read.

I've searched but I can not find any source that describes what this problem is nor how to fix it. Any ideas?

**Comment by Flameeyes** [comment]
This is the same as #223 and it's not coming from unpaper. Please report this to paperless-ngx because it clearly is caused by their setup.

**Comment by pheitman** [comment]
Sorry - I did search but didn't see issue #223. I've followed the directions from #223 to work around this problem and have asked for help on the paperless-ngx forum.
