### ISSUE TITLE
How to install

### ISSUE THREAD

**Issue by clarkk** [unpaper/unpaper#44]
Download and compile

```
# cd /var/bin && wget https://www.flameeyes.eu/files/unpaper-6.1.tar.xz && tar -xvf unpaper-6.1.tar.xz
# cd unpaper-6.1 && ./configure && make && make install
```

Error

```
configure: error: Package requirements (libavformat libavcodec libavutil) were not met:

No package 'libavformat' found
No package 'libavcodec' found
No package 'libavutil' found
```

Have tried

```
# apt-get install libavformat libavcodec libavutil
```

The packages is not found

**Comment by clarkk** [comment]
Have also tried to install `libav`

```
# cd /var/bin/ && git clone git://git.libav.org/libav.git && cd libav
# ./configure && make && make install
```

Error
```
# ./configure && make && make install
yasm/nasm not found or too old. Use --disable-yasm for a crippled build.

If you think configure made a mistake, make sure you are using the latest
version from Git.  If the latest version fails, report the problem to the
libav-tools@libav.org mailing list or IRC #libav on irc.freenode.net.
Include the log file "config.log" produced by configure as this will help
solving the problem.
```

**Comment by nitsnatsnok** [comment]
You just need to find the correct package names and install them. Considering you use Ubuntu 14.04 this would be: libavformat54 libavcodec54 libavutil52
If you use any other version or distribution you can find the package names by using your preferred package management software or online sources like http://packages.ubuntu.com/search?suite=trusty&keywords=libavcodec for Ubuntu packages. Or you could search your sources directly using e.g. apt-cache search libavformat – this simply lists the package names whose name or description matches libavformat.

**Comment by clarkk** [comment]
I'm on Debian

Have now searched for the libraries and found these

```
# apt-get install libavformat56 libavcodec56 libavutil54
```

But still get the same errors.. The same dependencies are missing

**Comment by clarkk** [comment]
The compiler is now asking for `xsltproc` so I installed it `apt-get install xsltproc`

But when `./configure && make && make install` I get this

```
config.status: executing depfiles commands
  CC       unpaper-file.o
  CC       unpaper-imageprocess.o
  CC       unpaper-parse.o
  CC       unpaper-tools.o
  CC       unpaper-unpaper.o
  CCLD     unpaper
make[1]: Entering directory '/var/bin/unpaper-6.1'
 /bin/mkdir -p '/usr/local/bin'
  /usr/bin/install -c unpaper '/usr/local/bin'
 /bin/mkdir -p '/usr/local/share/doc/unpaper'
 /usr/bin/install -c -m 644 NEWS COPYING README.md AUTHORS '/usr/local/share/doc/unpaper'
 /bin/mkdir -p '/usr/local/share/doc/unpaper'
 /usr/bin/install -c -m 644 doc/basic-concepts.md doc/image-processing.md doc/file-formats.md '/usr/local/share/doc/unpaper'
 /bin/mkdir -p '/usr/local/share/doc/unpaper/img'
 /usr/bin/install -c -m 644 doc/img/blackfilter-detail.png doc/img/blackfilter.png doc/img/blurfilter-detail.png doc/img/blurfilter.png doc/img/border-align.png doc/img/border-scan.png doc/img/deskew-detail1.png doc/img/deskew-detail2.png doc/img/deskew.png doc/img/documentation.odg doc/img/input-pages.png doc/img/layout-templates.png doc/img/mask-center.png doc/img/mask-scan-detail1.png doc/img/mask-scan-detail2.png doc/img/mask-scan.png doc/img/multiple-input-files.png doc/img/multiple-output-files.png doc/img/noisefilter.png doc/img/output-pages.png doc/img/processing-order.png doc/img/sheetspages.png doc/img/standard-deviation.png '/usr/local/share/doc/unpaper/img'
 /bin/mkdir -p '/usr/local/share/man/man1'
 /usr/bin/install -c -m 644 unpaper.1 '/usr/local/share/man/man1'
make[1]: Leaving directory '/var/bin/unpaper-6.1'
```

**Comment by clarkk** [comment]
Ok, now I got it compilled and installed..

But when a file is runned throug `unpaper` like this

```
# unpaper 1.png out.png
Processing sheet #1: 1.png -> out.png
out of deviation range - NO ROTATING
```

The output file is damaged or corrupted when you try to open it!?

**Comment by nitsnatsnok** [comment]
Try running it with verbose output (Options -v or even -vv), it will show you on which step the error occured. In this case I assume it’s an issue of the deskew scan, which can be influenced by the following options:
-dn { left | top | right | bottom },..., --deskew-scan-direction { left | top | right | bottom },...
           (… … …) (default: left,right)

       -ds pixels, --deskew-scan-size pixels
           Size of virtual line for rotation detection. (default: 1500)

       -dd ratio, --deskew-scan-depth ratio
           Amount of dark pixels to accumulate until scanning is stopped, relative to scan-bar size. (default: 0.5)

       -dr degrees, --deskew-scan-range degrees
           Range in which to search for rotation, from -degrees to +degrees rotation. (default: 5.0)

       -dp degrees, --deskew-scan-step degrees
           Steps between single rotation-angle detections. Lower numbers lead to better results but slow down processing. (default: 0.1)

       -dv deviation, --deskew-scan-deviation deviation
           Maximum statistical deviation allowed among the results from detected edges. No rotation if exceeded.

My way in coping with an error like that is determining which edge caused the error (see verbose output) and setting other edges using -dn. Altering the deviation with -dv can help avoiding the error, but won't fix it.

**Comment by gingerlime** [comment]
I'm using Ubuntu 14.04 and have those packages installed, but when I try to run `./configure` it complains  that they are not installed... Any tips?

```
$ sudo apt-get install libavformat54 libavcodec54 libavutil52                                                                                                                                          [63/829]
Reading package lists... Done
Building dependency tree       
Reading state information... Done
libavcodec54 is already the newest version.
libavcodec54 set to manually installed.
libavformat54 is already the newest version.
libavformat54 set to manually installed.
libavutil52 is already the newest version.
libavutil52 set to manually installed.

#...

$ ./configure 
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking whether make supports nested variables... (cached) yes
checking whether to enable maintainer-specific portions of Makefiles... yes
checking for style of include used by make... GNU
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking dependency style of gcc... gcc3
checking for gcc option to accept ISO C99... -std=gnu99
checking how to run the C preprocessor... gcc -std=gnu99 -E
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking minix/config.h usability... no
checking minix/config.h presence... no
checking for minix/config.h... no
checking whether it is safe to define __EXTENSIONS__... yes
checking for stdbool.h that conforms to C99... yes
checking for _Bool... yes
checking for library containing sqrt... -lm
checking for pkg-config... /usr/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for LIBAV... no
configure: error: Package requirements (libavformat libavcodec libavutil) were not met:

No package 'libavformat' found
No package 'libavcodec' found
No package 'libavutil' found

Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.

Alternatively, you may set the environment variables LIBAV_CFLAGS
and LIBAV_LIBS to avoid the need to call pkg-config.
See the pkg-config man page for more details.
```

**Comment by nitsnatsnok** [comment]
I assume you tried to install a newer version than supported by Ubuntu 14.04, I tried this as well and failed. :) The package `<unpaper>` from the sources provides version 0.4.2, just use this.
There are just a few months until 16.04 Xenial is released, and [its sources will officially provide](http://packages.ubuntu.com/xenial/unpaper) the currently freshest version 0.6.1, I think it's not worth the trouble fiddling…

**Comment by gingerlime** [comment]
Thanks @nitsnatsnok. I was just about to post a note that I realized there's a package... Would be nice to have the latest and greatest, but for now I'm happy with the pre-built one :) definitely not worth the trouble fiddling with dependencies etc.

**Comment by buhtz** [comment]
Close

**Comment by galegosimpatico** [comment]
@clarkk

> Have also tried to install libav
> 
> ```
> [...]
> ```
> 
> Error
> 
> ```
> [...]
> ```

You probably figured out, you fix that installing `nasm` for example.

But I wonder, how did you make `configure` detecting the libav residing in `/usr/local/`? Do you remember by chance?
