### ISSUE TITLE
pre-rotate 90 post-rotate 90 is not convoluted; it's broken

### ISSUE THREAD

**Issue by 257** [unpaper/unpaper#48]
[unpaper -vv --overwrite --no-processing 1-100 --pre-rotate 90 --post-rotate 90 %03d.pbm out/%03d.pbm
](https://gist.github.com/de6e88b036922e1cb8172676d0cfa88a) [gist]

**Comment by ccaccb** [comment]
This crash isn't caused by pre- or post-rotate but by incorrect memory reallocation in multi-index parsing.
Removing using e.g. `--no-processing 1` works.
