### ISSUE TITLE
unpaper-6 out yet . . .

### ISSUE THREAD

**Issue by Albretch** [unpaper/unpaper#53]
as in this previous issue: https://github.com/Flameeyes/unpaper/issues/21 

I am also getting:

Processing sheet #1: /tmp/s.ppm -> /tmp/s.ppm
*** error: input file format using magic '�+' is unknown.

<blockquote>
 Flameeyes commented Aug 9, 2014

This is fixed by chance in the libav-input branch. I plan to release that as unpaper-6 sometimes this month or in September at the latest.

In the new version the files are only opened for the time that it requires to read or write them.
</blockquote>

 Is unpaper-6 out yet or do we have a way to work around that issue?

 lbrtchx

**Comment by slokhorst** [comment]
[unpaper-6](https://github.com/Flameeyes/unpaper/releases/tag/unpaper-6) was released on August 19, 2014.

**Comment by Flameeyes** [comment]
I just released unpaper-7.0.0.
