### ISSUE TITLE
ubuntu 18.04 install failed

### ISSUE THREAD

**Issue by muralikodali** [unpaper/unpaper#72]
build fails with following error:

./configure: line 4652: syntax error near unexpected token `LIBAV,'
./configure: line 4652: `PKG_CHECK_MODULES(LIBAV, libavformat libavcodec libavutil)'

libav 12 installed on machine.

**Comment by Flameeyes** [comment]
The new Meson build should solve this issue (which is actually just a missing pkg-config-devel package).
