### ISSUE TITLE
Do the opposite: make it look like it was scanned

### ISSUE THREAD

**Issue by barraponto** [unpaper/unpaper#80]
I recently saw the service http://lookslikescanned.com/ that promises just that: send a pdf, get a looks-like-it-was-scanned copy of the pdf. There are glaring privacy issues with the service model, though. I decided to bring it up here in case there is already an open source alternative or to make the case for writing a new one. [doc/image-processing.md](https://github.com/unpaper/unpaper/blob/main/doc/image-processing.md) has great guide to get started.

**Comment by Flameeyes** [comment]
I'm sorry but I don't think this is the right project to implement this in.

Given it's been pretty much a one-person project, adding a completely opposite feature is a no-go option.

Feel free to use any processing code from this (following the license) but I wouldn't be merging the code back here.
