### ISSUE TITLE
Issue Compiling on Ubuntu 20.04 WSL

### ISSUE THREAD

**Issue by jacobcroope** [unpaper/unpaper#91]
Windows WSL 20.04 I have ffmeg installed but it's throwing errors. 

The Meson build system
Version: 0.58.0
Source dir: /home/jacob/unpaper
Build dir: /home/jacob/unpaper/builddir
Build type: native build
Project name: unpaper
Project version: undefined
C compiler for the host machine: cc (gcc 9.3.0 "cc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0")
C linker for the host machine: cc ld.bfd 2.34
Host machine cpu family: x86_64
Host machine cpu: x86_64
Checking for function "strdup" : YES
Compiler for C supports arguments -Werror=int-conversion: YES
Found pkg-config: /usr/bin/pkg-config (0.29.1)
Found CMake: /usr/bin/cmake (3.16.3)
Run-time dependency libavformat found: NO (tried pkgconfig and cmake)

meson.build:23:0: ERROR: Dependency "libavformat" not found, tried pkgconfig and cmake

From the Log: 

Compiler for C supports arguments -Werror=int-conversion: YES
Pkg-config binary for MachineChoice.HOST is not cached.
Pkg-config binary missing from cross or native file, or env var undefined.
Trying a default Pkg-config fallback at pkg-config
Found pkg-config: /usr/bin/pkg-config (0.29.1)
Determining dependency 'libavformat' with pkg-config executable '/usr/bin/pkg-config'
env[PKG_CONFIG_PATH]:
Called `/usr/bin/pkg-config --modversion libavformat` -> 1

CMake binary for MachineChoice.HOST is not cached
CMake binary missing from cross or native file, or env var undefined.
Trying a default CMake fallback at cmake
Found CMake: /usr/bin/cmake (3.16.3)
Extracting basic cmake information
Try CMake generator: auto
Calling CMake (['/usr/bin/cmake']) in /home/jacob/unpaper/builddir/meson-private/cmake_libavformat with:
  - "--trace"
  - "--trace-expand"
  - "--no-warn-unused-cli"
  - "--trace-redirect=cmake_trace.txt"
  - "-DCMAKE_TOOLCHAIN_FILE=/home/jacob/unpaper/builddir/meson-private/cmake_libavformat/CMakeMesonToolchainFile.cmake"
  - "."
  -- Module search paths:    ['/', '/opt', '/usr', '/usr/local']
  -- CMake root:             /usr/share/cmake-3.16
  -- CMake architectures:    ['x86_64-linux-gnu']
  -- CMake lib search paths: ['lib', 'lib32', 'lib64', 'libx32', 'share', 'lib/x86_64-linux-gnu']
Preliminary CMake check failed. Aborting.
Run-time dependency libavformat found: NO (tried pkgconfig and cmake)

meson.build:23:0: ERROR: Dependency "libavformat" not found, tried pkgconfig and cmake

**Comment by Flameeyes** [comment]
You'll need to install `libavformat-dev` (as well as `libavutil-dev` and `libavcodec-dev`) for this to be detected. Otherwise it only brings the runtime libraries.
