### ISSUE TITLE
Unpaper does not work with latest libavformat (59)

### ISSUE THREAD

**Issue by srini8080** [unpaper/unpaper#98]
encoding and decoding changed (now send and receive packets and frames) and so did filename (now url) and codec(now codecpar) fields changed.

Any plans to port it to support the latest libavformat?

**Comment by Flameeyes** [comment]
I guess I'll have to see the API changes and make a new release. Maybe weekend after next, unless something else comes before that. Or if someone sends a pull request.

**Comment by srini8080** [comment]
I tried something for 15 mins. But could not proceed. I am sure it will take you only a few minutes. The send and receive is where I do not know much.

30c30
<   int ret;
---
>   int ret, got_frame = 0;
55c55
<   if (s->streams[0]->codecpar->codec_type != AVMEDIA_TYPE_VIDEO)
---
>   if (s->streams[0]->codec->codec_type != AVMEDIA_TYPE_VIDEO)
58c58
<   ret = avcodec_parameters_to_context(avctx, s->streams[0]->codecpar);
---
>   ret = avcodec_copy_context(avctx, s->streams[0]->codec);
83,84c83
<   ret = avcodec_send_packet(avctx, &pkt);
<   ret = avcodec_receive_frame(avctx, frame);
---
>   ret = avcodec_decode_video2(avctx, frame, &got_frame, &pkt);
120d117
< 
154,155c151
<   out_ctx->url = av_malloc(sizeof(filename)+16);
<   snprintf(out_ctx->url, sizeof(filename), "%s", filename);
---
>   snprintf(out_ctx->filename, sizeof(out_ctx->filename), "%s", filename);
214,215c209,211
<   AVPacket *pkt;
<   pkt = av_packet_alloc();
---
>   AVPacket pkt = {0};
>   int got_packet;
>   av_init_packet(&pkt);
218,220c214
< 
<   ret = avcodec_send_frame(codec_ctx, output);
<   ret = avcodec_receive_packet(codec_ctx, pkt);
---
>   ret = avcodec_encode_video2(video_st->codec, &pkt, output, &got_packet);
226c220
<   av_write_frame(out_ctx, pkt);
---
>   av_write_frame(out_ctx, &pkt);

**Comment by srini8080** [comment]
Hi Diego,

Do you think, you will have some time for this?

Thanks,

**Comment by Flameeyes** [comment]
This was fixed in January and should be addressed with unpaper-7.0.0

**Comment by srini8080** [comment]
Thanks much
    On Thursday, April 21, 2022, 02:05:54 AM GMT+5:30, Diego Elio Pettenò ***@***.***> wrote:  
 
 


This was fixed in January and should be addressed with unpaper-7.0.0
